//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViralizeDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class NIVEL_LOG
    {
        public int id { get; set; }
        public int nivel_id { get; set; }
        public string op { get; set; }
        public System.DateTime fecha { get; set; }
    }
}
