//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViralizeDesktop
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_LOGRO
    {
        public int id { get; set; }
        public int usuarioID { get; set; }
        public int logroID { get; set; }
        public System.DateTime fechaObtencion { get; set; }
    
        public virtual LOGRO LOGRO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
